name: Generate Metrics
on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: dawoodkhatri1
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Karachi
