name: Pinned repositories
on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.repositories.pinned.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: dawoodkhatri1
          template: classic
          base: ""
          plugin_repositories: yes
          plugin_repositories_pinned: 2
          config_timezone: Asia/Karachi
