name: Recently starred
on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.stars.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: dawoodkhatri1
          template: classic
          base: ""
          plugin_stars: yes
          plugin_stars_limit: 3
          config_timezone: Asia/Karachi
